### PR TITLE
Solve many UVA problems

### PR DESCRIPTION
**Pull request by fatosmorina**
This is a list of solutions to many UVA problems.

### CODE REVIEW

**Comment by kdn251** [comment]
Hi @fatosmorina, thank you for the PR. Sorry for the late response, I am reviewing your solutions now!

**Comment by kdn251** [comment]
Hi @fatosmorina I have begun reviewing your changes; however, before I continue I would like you to please change "static void solve()" to "public static void main(String args[])" for all of your files in order to maintain the consistency of the repository. Please let me know when you have done so and I will continue reviewing your PR. Thank you!

**Comment by fatosmorina** [comment]
Hi @kdn251 

I have made the changes you asked for. Can you please continue with the review now?

Thanks.

**Comment by kdn251** [comment]
Hi @fatosmorina thank you so for your patience. I'm committing your changes now! Looking forward to more of your contributions :)

**Comment by fatosmorina** [comment]
Hi @kdn251 

Thank you too for giving me the opportunity to contribute in your helpful repository. I am honored and privileged.

**Pull request merged**
