### PR TITLE
Added image binary tree type

### PR DESCRIPTION
**Pull request by jsroyal**

### CODE REVIEW

**Comment by jsroyal** [comment]
Hey! @kdn251 review it please.

**Comment by jsroyal** [comment]
Hey! @EugenHotaj,  Yeah! Image quality is bad. So is there way to draw graph in markdown language or need to draw in latex and again take screenshots. Is that right? 
Where to upload ? Can you give link me?

**Comment by EugenHotaj** [comment]
Hey @jsroyal, sorry for the late response. As far as I know, you cannot draw graphs in markdown, but latex will definitely work, though there are better ways out there, like graphviz: http://stackoverflow.com/questions/7020741/drawing-rendering-multiway-tree-in-python (bonus points if you can somehow use svgs). 

As far as where to put the images, why not just put them in the existing Images folder: https://github.com/kdn251/interviews/tree/master/Images.

Then you can refer to them via relative paths instead of absolute paths.

**Comment by jsroyal** [comment]
@EugenHotaj Okay so you want to first create a tree graph and take screenshots and upload https://github.com/kdn251/interviews/tree/master/Images.

But the question how to upload this link and also did not get relative path/absolute paths?
could you please clear it?

**Comment by EugenHotaj** [comment]
You don't upload to this link. You should have access to the "Images" directory whenever your fork this repo, so just put your images there. Then, when you modify the Readme file, refer to them via a relative link instead of an absolute link: src="/Images/<your_image_name_here>". 

Then, if @kdn251 decides to merge your pull request, the images will also be merge instead of being in your repo. 

Google is your friend here, so if there's something you don't understand, just look it up: https://en.wikipedia.org/wiki/Path_(computing)#Absolute_and_relative_paths.

**Comment by EugenHotaj** [comment]
No response in almost a month. Closing this out. Please feel free to reopen if anything changes.

**Comment by chengzx** [comment]
i'm sorry,   wrong operation 发自网易邮箱大师 在2017年04月08日 04:28，Eugen Hotaj 写道： No response in almost a month. Closing this out. Please feel free to reopen if anything changes. — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or mute the thread.

**Pull request closed without merging**
